### ISSUE TITLE
To Determine WireFrame

### ISSUE THREAD

**Issue by Jason897571** [Jason897571/Magical-Book-Browser#1]

**Comment by Jason897571** [comment]
To determine the framework

**Comment by Jason897571** [comment]
Wireframe 
![wireframe](https://github.com/Jason897571/Magical-Book-Browser/assets/67337624/6d535a2e-0019-4b19-a508-fe294651a893)

**Comment by Jason897571** [comment]
Applied Muniba's wireframe
![image](https://github.com/Jason897571/Magical-Book-Browser/assets/67337624/919f306f-5c29-4e91-9d7d-871ad4113b1e)

**Comment by topcowmoo** [comment]
Here is my wireframe:

<img width="1138" alt="Magical Book Browser Wireframe" src="https://github.com/Jason897571/Magical-Book-Browser/assets/149528212/0c1a3f35-0f87-4993-a2ac-640d15f26d9e">
